export interface ProcessStep {
  id: string
  title: string
  description: string
  type: "info" | "question" | "action" | "validation"
  content: string
  options?: {
    id: string
    label: string
    nextStep?: string
    action?: string
  }[]
  nextStep?: string
  warning?: string
  tip?: string
  estimatedTime?: string
}

export interface Process {
  id: string
  title: string
  description: string
  category: string
  steps: number
  avgTime: string
  difficulty: "Fácil" | "Medio" | "Difícil"
  usage: number
  lastUpdated: string
}

export interface ProcessCategory {
  id: string
  title: string
  description: string
  icon: string
  color: string
  processes: number
  avgTime: string
  href: string
}

// Categorías de procesos de Clivi
export const processCategories: ProcessCategory[] = [
  {
    id: "cancelacion",
    title: "Cancelación",
    description: "Proceso de cancelación de pacientes y retención",
    icon: "UserMinus",
    color: "bg-red-500",
    processes: 1,
    avgTime: "8-15 min",
    href: "/processes/cancelacion",
  },
  {
    id: "medicamento",
    title: "Envío de Medicamento",
    description: "Gestión de envíos de medicamentos a pacientes",
    icon: "Pill",
    color: "bg-green-500",
    processes: 1,
    avgTime: "5-8 min",
    href: "/processes/medicamento",
  },
  {
    id: "pagos",
    title: "Gestión de Pagos",
    description: "Cambio de fecha, adelanto de pago y errores de pago",
    icon: "CreditCard",
    color: "bg-purple-500",
    processes: 3,
    avgTime: "4-10 min",
    href: "/processes/pagos",
  },
  {
    id: "envios",
    title: "Envíos y Entregas",
    description: "Error en dirección, confirmación de delivery",
    icon: "Truck",
    color: "bg-blue-500",
    processes: 1,
    avgTime: "3-5 min",
    href: "/processes/envios",
  },
  {
    id: "citas",
    title: "Citas y Seguimiento",
    description: "Agendamiento de citas y flujo de pacientes",
    icon: "Calendar",
    color: "bg-cyan-500",
    processes: 2,
    avgTime: "5-10 min",
    href: "/processes/citas",
  },
]

// Lista de procesos
export const processList: Record<string, Process[]> = {
  cancelacion: [
    {
      id: "proc-cancelacion",
      title: "Cancelación de Paciente",
      description: "Proceso completo de cancelación con opciones de retención",
      category: "cancelacion",
      steps: 15,
      avgTime: "10-15 min",
      difficulty: "Difícil",
      usage: 89,
      lastUpdated: "Hoy",
    },
  ],
  medicamento: [
    {
      id: "proc-envio-medicamento",
      title: "Envío de Medicamento",
      description: "Proceso para gestionar envíos de medicamento",
      category: "medicamento",
      steps: 7,
      avgTime: "5-8 min",
      difficulty: "Medio",
      usage: 156,
      lastUpdated: "Hoy",
    },
  ],
  pagos: [
    {
      id: "proc-cambio-fecha-pago",
      title: "Cambio Fecha de Pago",
      description: "Modificar la fecha de cobro del paciente",
      category: "pagos",
      steps: 4,
      avgTime: "4-6 min",
      difficulty: "Fácil",
      usage: 134,
      lastUpdated: "Hoy",
    },
    {
      id: "proc-adelanto-pago",
      title: "Adelanto de Pago",
      description: "Adelantar pago por envío de medicamento",
      category: "pagos",
      steps: 8,
      avgTime: "8-12 min",
      difficulty: "Medio",
      usage: 98,
      lastUpdated: "Hoy",
    },
    {
      id: "proc-payment-error",
      title: "Payment Error",
      description: "Gestión de errores de pago y facturas con deuda",
      category: "pagos",
      steps: 6,
      avgTime: "6-10 min",
      difficulty: "Medio",
      usage: 112,
      lastUpdated: "Hoy",
    },
  ],
  envios: [
    {
      id: "proc-error-direccion",
      title: "Error en Dirección de Entrega",
      description: "Corrección de dirección de envío",
      category: "envios",
      steps: 8,
      avgTime: "3-5 min",
      difficulty: "Medio",
      usage: 78,
      lastUpdated: "Hoy",
    },
  ],
  citas: [
    {
      id: "proc-flujo-px-sin-cita",
      title: "Flujo PX sin Cita (Segundo Pago Próximo)",
      description: "Proceso para pacientes sin cita con segundo pago próximo",
      category: "citas",
      steps: 12,
      avgTime: "5-8 min",
      difficulty: "Medio",
      usage: 87,
      lastUpdated: "Hoy",
    },
    {
      id: "proc-agendamiento-citas",
      title: "Agendamiento de Citas",
      description: "Proceso para agendar citas primera vez y subsecuentes",
      category: "citas",
      steps: 4,
      avgTime: "3-5 min",
      difficulty: "Fácil",
      usage: 145,
      lastUpdated: "Hoy",
    },
  ],
}

// Pasos detallados de cada proceso
export const processSteps: Record<string, ProcessStep[]> = {
  "proc-cancelacion": [
    {
      id: "step-1",
      title: "¿El paciente se comunica para cancelar o para dar seguimiento a su cancelación?",
      description: "Identificar el motivo principal de la comunicación",
      type: "question",
      content: "Preguntar si el paciente está llamando para cancelar o para dar seguimiento a una cancelación previa.",
      options: [
        {
          id: "seguimiento",
          label: "Seguimiento",
          nextStep: "step-seguimiento",
        },
        {
          id: "cancelar",
          label: "Cancelar",
          nextStep: "step-cancelar",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-seguimiento",
      title: "Validar Churn y Agendar",
      description: "Proceso de seguimiento para pacientes con cancelación previa",
      type: "action",
      content: "Paso 1: Validar que tenga un Churn para cancelación y quien lo tiene Asignado.\n\nPaso 2: Pedir al paciente un día para agendar y un rango de horario.\n\nPaso 3: Validar horarios disponibles con el paciente de acuerdo al calendario que visualizamos, confirmar horario con el paciente.\n\nPaso 4: Seleccionar el horario y llenar los campos de Nombre y Apellido con los datos del PX.\n\nPaso 5: En el campo de correo electrónico poner el correo del paciente registrado con Clivi.\n\nPaso 6: Mencionar al paciente el horario en el que le estarían marcando, confirmar que la información sea clara.\n\nPaso 7: Marcar como Resuelto",
      nextStep: "step-resuelto",
      tip: "Ser muy empático y defensor del paciente durante todo el proceso",
      estimatedTime: "8 minutos",
    },
    {
      id: "step-cancelar",
      title: "Preguntar Motivo de Cancelación",
      description: "Identificar la razón específica de la cancelación",
      type: "question",
      content: "Preguntar el motivo específico de la cancelación para determinar la mejor acción.",
      options: [
        {
          id: "motivos-medicos",
          label: "Por motivos médicos (No se siente bien, tiene que continuar con algún otro tratamiento, se encuentra muy enfermo)",
          nextStep: "step-gestion-especialista",
        },
        {
          id: "meta-alcanzada",
          label: "Ya llegó a su meta esperada",
          nextStep: "step-downgrade",
        },
        {
          id: "economicas-baja",
          label: "Ya no lo puede pagar por cuestiones económicas",
          nextStep: "step-churn-baja",
        },
        {
          id: "no-quiere-medicamento",
          label: "Ya no puede pagar porque no quiere el medicamento",
          nextStep: "step-downgrade",
        },
        {
          id: "problema-envio",
          label: "Complicaciones con el envío de insumos",
          nextStep: "step-reenvio-insumos",
        },
        {
          id: "conflicto-especialista",
          label: "Algún conflicto con algún especialista",
          nextStep: "step-cambiar-especialista",
        },
      ],
      estimatedTime: "2 minutos",
    },
    {
      id: "step-gestion-especialista",
      title: "Gestión de Especialista",
      description: "Para motivos médicos",
      type: "action",
      content: "Generar Task por 'Queja'\n\nSi corresponde cita subsecuente se genera cambio de especialista en Calendly como agendamiento de cita de primera vez (Long)",
      nextStep: "step-razon-ingreso",
      tip: "Validar sus citas agendadas, por si es posible reagendar su cita",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-downgrade",
      title: "Downgrade",
      description: "Proceso de reducción o eliminación de medicamento",
      type: "action",
      content: "Se realiza disminución de dosis, cuando las dosis son altas ejemplo (Wegovy 1.8 en adelante a baja de dosis de 1mg). O se elimina el medicamento.\n\nSeleccionar al especialista como 'Gestión de especialista a Balance' y creación de Task a Salud (Admin)",
      nextStep: "step-razon-ingreso",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-churn-baja",
      title: "Churn de Baja",
      description: "Proceso de baja solicitada por el paciente",
      type: "action",
      content: "Si la solicita, se realiza Churn de Baja",
      nextStep: "step-razon-ingreso",
      tip: "Documentar claramente que el paciente solicitó la baja",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-reenvio-insumos",
      title: "Re-envío de Insumos",
      description: "Gestión de envío de insumos",
      type: "action",
      content: "Identificar si aplica envio de insumos → Seguir proceso de envío de medicamentos",
      nextStep: "step-razon-ingreso",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-cambiar-especialista",
      title: "Cambiar de Especialista",
      description: "Cambio de especialista por conflicto",
      type: "action",
      content: "Buscar el seguimiento con algún otro especialista disponible → Seguir proceso de agendar cita",
      nextStep: "step-razon-ingreso",
      tip: "Generar Task por 'Queja' si corresponde",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-razon-ingreso",
      title: "Preguntar Razón de Ingreso",
      description: "Identificar el plan del paciente",
      type: "question",
      content: "Preguntar la razón de ingreso para determinar el plan y beneficios disponibles.",
      options: [
        {
          id: "diabetes",
          label: "Diabetes",
          nextStep: "step-contencion",
        },
        {
          id: "zero",
          label: "Zero",
          nextStep: "step-contencion",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-contencion",
      title: "Contención y Retención",
      description: "Proceso de contención del paciente",
      type: "action",
      content: "Ser muy empáticos y defensores del paciente\n\nIdeas de retención:\n\n• Gestión de Especialista: Validar sus citas agendadas, por si es posible reagendar su cita → Seguir proceso de Agendamiento de cita\n\n• Cambio de especialista: Buscar el seguimiento con algún otro especialista disponible → Seguir proceso de agendar cita\n\n• Envío de insumos: Identificar si aplica envio de insumos → Seguir proceso de envío de medicamentos\n\n• Downgrade: Se realiza disminución de dosis o eliminación de medicamento",
      nextStep: "step-confirmar-cancelacion",
      tip: "Mostrar empatía genuina y buscar soluciones alternativas",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-confirmar-cancelacion",
      title: "¿El paciente quiere cancelar?",
      description: "Confirmación final de cancelación",
      type: "question",
      content: "Confirmar si después de las opciones de retención, el paciente aún desea cancelar.",
      options: [
        {
          id: "no-cancelar",
          label: "NO - No quiere cancelar",
          nextStep: "step-ticket-seguimiento",
        },
        {
          id: "si-cancelar",
          label: "SI - SI Quiere cancelar",
          nextStep: "step-paciente-molesto",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-ticket-seguimiento",
      title: "Crear Ticket de Seguimiento",
      description: "Creación de ticket para seguimiento",
      type: "action",
      content: "Hacer Ticket para dar un seguimiento y dejar nota\n\nSe marca como Resuelto",
      nextStep: "step-resuelto",
      tip: "Documentar claramente el motivo del seguimiento",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-paciente-molesto",
      title: "¿El paciente está muy molesto?",
      description: "Evaluar el estado emocional del paciente",
      type: "question",
      content: "Evaluar si el paciente está muy molesto para determinar el nivel de escalación.",
      options: [
        {
          id: "no-molesto",
          label: "NO - Cerrar como Resuelto",
          nextStep: "step-guia-practica",
        },
        {
          id: "si-molesto",
          label: "SI - El paciente está muy molesto",
          nextStep: "step-escalar-molesto",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-guia-practica",
      title: "Guía Práctica de Baja",
      description: "Proceso de baja estándar",
      type: "action",
      content: "Se realiza Guía Práctica de solicitud de baja\n\nSe redacta nota\n\nExplicar que se van a comunicar con él (Área de Churn - es baja), se escala por medio del Chat de Gmail al grupo 'Nivel 2: Retención Soporte (Asunto Money)' arrobando a la persona que tiene el ticket asignado\n\nAbrir el calendario de retenciones. Seleccionar la persona que tiene asignado el Churn.",
      nextStep: "step-resuelto",
      tip: "Ser claro y empático en la explicación del proceso",
      estimatedTime: "5 minutos",
    },
    {
      id: "step-escalar-molesto",
      title: "Escalar Paciente Molesto",
      description: "Escalado por paciente molesto",
      type: "action",
      content: "Se escala por medio del Chat de Gmail al grupo 'Nivel 2: Retención Soporte (Asunto Money)' Arrobando a la persona que tiene el ticket asignado\n\nCompartir link del perfil de Hubspot y describir la situación.",
      nextStep: "step-resuelto",
      tip: "Documentar detalladamente la situación y motivo del enojo",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-resuelto",
      title: "Proceso Completado",
      description: "Proceso de cancelación finalizado",
      type: "info",
      content: "El proceso de cancelación ha sido completado exitosamente. Marcar como Resuelto en Hubspot.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-envio-medicamento": [
    {
      id: "step-1",
      title: "¿Es Envío de Primera vez?",
      description: "Determinar si es el primer envío o uno subsecuente",
      type: "question",
      content: "Preguntar si es el primer envío de medicamento para el paciente.",
      options: [
        {
          id: "primera-vez",
          label: "SI - Es envio de primera vez",
          nextStep: "step-primera-vez",
        },
        {
          id: "subsecuente",
          label: "NO - Es envío subsecuente",
          nextStep: "step-subsecuente",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-primera-vez",
      title: "Proceso de Primera Vez",
      description: "Pasos para envío de primera vez",
      type: "action",
      content: "Paso 1: Indicarle que tarda aproximadamente 2 días en hacerse el envío de medicamento después de su cita.\n\nPaso 2: Validar en Admin, en el apartado de 'Feed', en la fila de 'Delivery' dar clic en la fila y revisar en 'Detalles de la orden' en la sección derecha de historial.\n\nPaso 3: En el apartado de 'Historial' validar en la columna de 'Delivery Status' y 'Operator', en la segunda fila tiene que aparecer 'Order Validated' y el nombre de alguna persona.\n\nPaso 4: Si ya se encuentra validado. Compartir la liga de rastreo de la paquetería y mencionar con el paciente que tarda de 5 hasta 7 días hábiles. Si es día viernes se estaría enviando hasta el dia lunes (sábado y domingo no se realizan envios)\n\nADET - Paqueteria en CDMX\nDHL - Paqueteria\nRepartidora Local - 10 kilómetros a la redonda de la oficina\nEntrega en oficina CLIVI - Dirección en oficinas",
      nextStep: "step-completado",
      tip: "Explicar claramente los tiempos de entrega y paqueterías disponibles",
      estimatedTime: "5 minutos",
    },
    {
      id: "step-subsecuente",
      title: "Proceso Subsecuente",
      description: "Pasos para envíos subsecuentes",
      type: "action",
      content: "Paso 1: Revisar Chargebee\nValidar fechas de Pago\nValidar que el pago se encuentre en Status 'PAID'\n\nPaso 2: Confirmar el envio de medicamento\nValidar en Admin la fila de 'Delivery' en la sección de 'Feed'\n\nPaso 3: Compartir la liga de la rastreo de la paquetería y mencionar con el paciente que tarda de 5 hasta 7 días hábiles. Si es día viernes se estaría enviando hasta el dia lunes (sábado y domingo no se realizan envios)\n\nPaso 4: Compartir la liga del perfil del PX al grupo de Chat de Gmail de Supplies mencionando que se solicita el envio de medicamento",
      nextStep: "step-completado",
      tip: "Validar siempre que el pago esté en status PAID antes de confirmar envío",
      estimatedTime: "6 minutos",
    },
    {
      id: "step-completado",
      title: "Envío Confirmado",
      description: "Proceso de envío completado",
      type: "info",
      content: "El proceso de envío de medicamento ha sido completado. Se ha proporcionado información de rastreo al paciente.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-cambio-fecha-pago": [
    {
      id: "step-1",
      title: "Preguntar Fecha de Pago",
      description: "Consultar la fecha de pago actual del paciente",
      type: "question",
      content: "Preguntar al paciente: '¿Cuál es la fecha de pago que desea?'",
      nextStep: "step-2",
      estimatedTime: "1 minuto",
    },
    {
      id: "step-2",
      title: "Validar en Chargebee",
      description: "Verificar la fecha de pago actual en el sistema",
      type: "action",
      content: "Paso 1: Entrar a Chargebee\n\nPaso 2: Buscar al paciente\n\nPaso 3: Revisar la fecha de pago actual\n\nPaso 4: Validar que no tenga adeudo",
      nextStep: "step-3",
      tip: "Verificar siempre que no existan adeudos antes de cambiar la fecha",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-3",
      title: "Cambiar Fecha de Pago",
      description: "Realizar el cambio de fecha en el sistema",
      type: "action",
      content: "Paso 1: Dar clic en 'Subscription'\n\nPaso 2: Dar clic en 'Change Billing Date'\n\nPaso 3: Poner la fecha que el paciente solicitó\n\nPaso 4: Dar clic en 'Change Billing Date'\n\nPaso 5: Confirmar el cambio",
      nextStep: "step-4",
      tip: "Confirmar siempre el cambio con el paciente antes de finalizar",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-4",
      title: "Confirmación con Paciente",
      description: "Informar al paciente sobre el cambio realizado",
      type: "action",
      content: "Informar al paciente que se ha realizado el cambio de fecha de pago exitosamente.\n\nMencionar la nueva fecha de pago para confirmación.",
      nextStep: "step-completado",
      estimatedTime: "1 minuto",
    },
    {
      id: "step-completado",
      title: "Proceso Completado",
      description: "Cambio de fecha de pago finalizado",
      type: "info",
      content: "El proceso de cambio de fecha de pago ha sido completado exitosamente.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-adelanto-pago": [
    {
      id: "step-1",
      title: "Preguntar Razón del Adelanto",
      description: "Identificar el motivo del adelanto de pago",
      type: "question",
      content: "Preguntar al paciente la razón por la cual desea adelantar su pago.",
      options: [
        {
          id: "envio-medicamento",
          label: "Por envío de medicamento",
          nextStep: "step-validar-envio",
        },
        {
          id: "otra-razon",
          label: "Otra razón",
          nextStep: "step-evaluar-caso",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-validar-envio",
      title: "Validar Envío de Medicamento",
      description: "Verificar si aplica envío de medicamento",
      type: "action",
      content: "Paso 1: Revisar si el paciente tiene envíos pendientes\n\nPaso 2: Validar que no tenga adeudos\n\nPaso 3: Confirmar que el adelanto es para envío de medicamento",
      nextStep: "step-procesar-adelanto",
      tip: "Solo procesar adelantos si es para envío de medicamento",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-evaluar-caso",
      title: "Evaluar Caso Especial",
      description: "Evaluar si aplica para adelanto por otras razones",
      type: "action",
      content: "Evaluar el caso específico del paciente.\n\nConsultar con supervisor si es necesario.\n\nDocumentar la razón específica del adelanto.",
      nextStep: "step-procesar-adelanto",
      tip: "Documentar claramente cualquier caso especial",
      estimatedTime: "4 minutos",
    },
    {
      id: "step-procesar-adelanto",
      title: "Procesar Adelanto en Chargebee",
      description: "Realizar el adelanto de pago en el sistema",
      type: "action",
      content: "Paso 1: Entrar a Chargebee\n\nPaso 2: Buscar al paciente\n\nPaso 3: Dar clic en 'Subscription'\n\nPaso 4: Dar clic en 'Charge Now'\n\nPaso 5: Seleccionar la cantidad a adelantar\n\nPaso 6: Procesar el pago",
      nextStep: "step-confirmar-pago",
      tip: "Verificar que el pago se procese correctamente",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-confirmar-pago",
      title: "Confirmar Pago Procesado",
      description: "Verificar que el pago se haya procesado correctamente",
      type: "action",
      content: "Paso 1: Verificar que el aparezca como 'PAID'\n\nPaso 2: Confirmar el monto adelantado\n\nPaso 3: Validar la siguiente fecha de pago",
      nextStep: "step-notificar-paciente",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-notificar-paciente",
      title: "Notificar al Paciente",
      description: "Informar sobre el adelanto procesado",
      type: "action",
      content: "Informar al paciente que el adelanto de pago ha sido procesado exitosamente.\n\nMencionar el monto adelantado y la siguiente fecha de pago.\n\nSi fue por envío de medicamento, seguir el proceso de envío correspondiente.",
      nextStep: "step-completado",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-completado",
      title: "Adelanto Completado",
      description: "Proceso de adelanto de pago finalizado",
      type: "info",
      content: "El proceso de adelanto de pago ha sido completado exitosamente.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-payment-error": [
    {
      id: "step-1",
      title: "Identificar Error de Pago",
      description: "Determinar el tipo de error de pago",
      type: "question",
      content: "Preguntar al paciente sobre el error específico que está experimentando.",
      options: [
        {
          id: "tarjeta-rechazada",
          label: "Tarjeta rechazada",
          nextStep: "step-validar-tarjeta",
        },
        {
          id: "fondos-insuficientes",
          label: "Fondos insuficientes",
          nextStep: "step-ofrecer-planes",
        },
        {
          id: "factura-con-deuda",
          label: "Factura con deuda",
          nextStep: "step-gestionar-deuda",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-validar-tarjeta",
      title: "Validar Información de Tarjeta",
      description: "Verificar los datos de la tarjeta",
      type: "action",
      content: "Paso 1: Solicitar al paciente los datos de la tarjeta\n\nPaso 2: Verificar número, fecha de vencimiento y CVV\n\nPaso 3: Confirmar nombre del titular\n\nPaso 4: Validar que la tarjeta permita cargos internacionales",
      nextStep: "step-actualizar-tarjeta",
      tip: "Nunca almacenar datos de tarjetas en notas o chats",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-actualizar-tarjeta",
      title: "Actualizar Tarjeta en Chargebee",
      description: "Actualizar la información de pago",
      type: "action",
      content: "Paso 1: Entrar a Chargebee\n\nPaso 2: Buscar al paciente\n\nPaso 3: Dar clic en 'Payment Source'\n\nPaso 4: Actualizar la información de la tarjeta\n\nPaso 5: Guardar cambios",
      nextStep: "step-probar-pago",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-probar-pago",
      title: "Procesar Pago de Prueba",
      description: "Intentar procesar el pago",
      type: "action",
      content: "Paso 1: Intentar procesar el pago pendiente\n\nPaso 2: Verificar si el pago es exitoso\n\nPaso 3: Si falla, identificar el motivo específico",
      nextStep: "step-evaluar-resultado",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-ofrecer-planes",
      title: "Ofrecer Planes de Pago",
      description: "Presentar alternativas de pago",
      type: "action",
      content: "Paso 1: Explicar opciones de planes de pago\n\nPaso 2: Ofrecer fraccionamiento de deuda\n\nPaso 3: Presentar opciones de downgrade si aplica\n\nPaso 4: Acordar plan de pago con paciente",
      nextStep: "step-implementar-plan",
      tip: "Ser empático y flexible con las opciones de pago",
      estimatedTime: "4 minutos",
    },
    {
      id: "step-gestionar-deuda",
      title: "Gestionar Factura con Deuda",
      description: "Manejar facturas pendientes de pago",
      type: "action",
      content: "Paso 1: Identificar monto total de la deuda\n\nPaso 2: Revisar antigüedad de la factura\n\nPaso 3: Evaluar opciones de regularización\n\nPaso 4: Coordinar con equipo de cobranza si es necesario",
      nextStep: "step-regularizar-deuda",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-implementar-plan",
      title: "Implementar Plan de Pago",
      description: "Configurar el plan acordado",
      type: "action",
      content: "Paso 1: Configurar el plan de pago en Chargebee\n\nPaso 2: Establecer fechas y montos\n\nPaso 3: Confirmar configuración con paciente\n\nPaso 4: Enviar confirmación por correo",
      nextStep: "step-completado",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-regularizar-deuda",
      title: "Regularizar Deuda",
      description: "Procesar el pago de la deuda",
      type: "action",
      content: "Paso 1: Procesar pago de deuda total o parcial\n\nPaso 2: Actualizar estado de factura\n\nPaso 3: Confirmar regularización con paciente\n\nPaso 4: Programar próximos pagos si aplica",
      nextStep: "step-completado",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-evaluar-resultado",
      title: "Evaluar Resultado del Pago",
      description: "Verificar el estado final del pago",
      type: "action",
      content: "Paso 1: Verificar si el pago fue exitoso\n\nPaso 2: Si falló, ofrecer alternativas\n\nPaso 3: Documentar el resultado\n\nPaso 4: Escalar si es necesario",
      nextStep: "step-completado",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-completado",
      title: "Error de Pago Resuelto",
      description: "Proceso de error de pago finalizado",
      type: "info",
      content: "El proceso de gestión de error de pago ha sido completado. Se han tomado las acciones necesarias para resolver la situación.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-error-direccion": [
    {
      id: "step-1",
      title: "Identificar Error en Dirección",
      description: "Determinar el tipo de error en la dirección",
      type: "question",
      content: "Preguntar al paciente cuál es el problema específico con su dirección de entrega.",
      options: [
        {
          id: "direccion-incorrecta",
          label: "Dirección incorrecta o incompleta",
          nextStep: "step-verificar-direccion",
        },
        {
          id: "no-recibido",
          label: "No recibió el paquete",
          nextStep: "step-rastrear-paquete",
        },
        {
          id: "paquete-devuelto",
          label: "Paquete devuelto",
          nextStep: "step-gestionar-devolucion",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-verificar-direccion",
      title: "Verificar Dirección Correcta",
      description: "Obtener la dirección correcta del paciente",
      type: "action",
      content: "Paso 1: Solicitar al paciente su dirección completa\n\nPaso 2: Verificar calle, número, colonia, código postal\n\nPaso 3: Confirmar ciudad y estado\n\nPaso 4: Obtener referencias y teléfono de contacto\n\nPaso 5: Validar que la dirección sea correcta y completa",
      nextStep: "step-actualizar-direccion",
      tip: "Ser muy detallado en la verificación para evitar futuros errores",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-rastrear-paquete",
      title: "Rastrear Paquete",
      description: "Verificar el estado del envío",
      type: "action",
      content: "Paso 1: Obtener número de seguimiento\n\nPaso 2: Rastrear en sistema de paquetería\n\nPaso 3: Verificar estado actual del paquete\n\nPaso 4: Identificar si hubo intento de entrega\n\nPaso 5: Revisar si hay notas de entrega",
      nextStep: "step-evaluar-rastreo",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-gestionar-devolucion",
      title: "Gestionar Paquete Devuelto",
      description: "Manejar paquetes que fueron devueltos",
      type: "action",
      content: "Paso 1: Verificar motivo de la devolución\n\nPaso 2: Confirmar si el paquete está en oficinas\n\nPaso 3: Evaluar costos de reenvío\n\nPaso 4: Coordinar nuevo envío si aplica",
      nextStep: "step-coordinar-reeenvio",
      tip: "Documentar claramente el motivo de la devolución",
      estimatedTime: "4 minutos",
    },
    {
      id: "step-actualizar-direccion",
      title: "Actualizar Dirección en Sistema",
      description: "Corregir la dirección del paciente",
      type: "action",
      content: "Paso 1: Entrar al sistema de administración\n\nPaso 2: Buscar perfil del paciente\n\nPaso 3: Actualizar dirección completa\n\nPaso 4: Guardar cambios\n\nPaso 5: Confirmar actualización",
      nextStep: "step-coordinar-reeenvio",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-evaluar-rastreo",
      title: "Evaluar Resultados de Rastreo",
      description: "Analizar la información del rastreo",
      type: "action",
      content: "Paso 1: Analizar estado del paquete\n\nPaso 2: Identificar problema específico\n\nPaso 3: Determinar si necesita reenvío\n\nPaso 4: Coordinar con paquetería si es necesario",
      nextStep: "step-coordinar-reeenvio",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-coordinar-reeenvio",
      title: "Coordinar Reenvío",
      description: "Organizar el nuevo envío del paquete",
      type: "action",
      content: "Paso 1: Contactar al equipo de supplies\n\nPaso 2: Solicitar reenvío con nueva dirección\n\nPaso 3: Confirmar fecha de reenvío\n\nPaso 4: Obtener nuevo número de seguimiento\n\nPaso 5: Informar al paciente",
      nextStep: "step-confirmar-paciente",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-confirmar-paciente",
      title: "Confirmar con Paciente",
      description: "Informar al paciente sobre la solución",
      type: "action",
      content: "Paso 1: Explicar la solución implementada\n\nPaso 2: Proporcionar nuevo número de seguimiento\n\nPaso 3: Informar fecha estimada de entrega\n\nPaso 4: Proporcionar contacto para seguimiento",
      nextStep: "step-completado",
      tip: "Mantener al paciente informado durante todo el proceso",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-completado",
      title: "Error de Dirección Resuelto",
      description: "Proceso de corrección de dirección finalizado",
      type: "info",
      content: "El proceso de corrección de dirección ha sido completado. Se ha actualizado la información y coordinado el reenvío si era necesario.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-flujo-px-sin-cita": [
    {
      id: "step-1",
      title: "Validar Segundo Pago Próximo",
      description: "Confirmar que el paciente tiene segundo pago próximo",
      type: "question",
      content: "Preguntar al paciente: '¿Tiene usted un segundo pago próximo?'",
      options: [
        {
          id: "si-pago-proximo",
          label: "SI - Tiene segundo pago próximo",
          nextStep: "step-validar-sin-cita",
        },
        {
          id: "no-pago-proximo",
          label: "NO - No tiene segundo pago próximo",
          nextStep: "step-derivacion",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-validar-sin-cita",
      title: "Validar que no tenga cita agendada",
      description: "Verificar que el paciente no tenga cita programada",
      type: "action",
      content: "Paso 1: Revisar en Calendly si tiene cita agendada\n\nPaso 2: Verificar en Hubspot citas programadas\n\nPaso 3: Confirmar que no tenga cita próxima\n\nPaso 4: Validar que sea elegible para el flujo",
      nextStep: "step-agendar-cita",
      tip: "Verificar en múltiples sistemas para confirmar que no tenga cita",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-agendar-cita",
      title: "Agendar Cita",
      description: "Programar cita para el paciente",
      type: "action",
      content: "Paso 1: Abrir Calendly\n\nPaso 2: Seleccionar especialista disponible\n\nPaso 3: Buscar horarios disponibles\n\nPaso 4: Agendar cita de primera vez (Long)\n\nPaso 5: Llenar datos del paciente\n\nPaso 6: Confirmar agendamiento",
      nextStep: "step-confirmar-paciente",
      estimatedTime: "4 minutos",
    },
    {
      id: "step-confirmar-paciente",
      title: "Confirmar Cita con Paciente",
      description: "Informar al paciente sobre la cita agendada",
      type: "action",
      content: "Paso 1: Informar fecha y hora de la cita\n\nPaso 2: Mencionar nombre del especialista\n\nPaso 3: Explicar preparación para la cita\n\nPaso 4: Enviar confirmación por correo\n\nPaso 5: Proporcionar contacto para cambios",
      nextStep: "step-crear-ticket",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-crear-ticket",
      title: "Crear Ticket de Seguimiento",
      description: "Documentar el proceso en Hubspot",
      type: "action",
      content: "Paso 1: Crear ticket en Hubspot\n\nPaso 2: Documentar el flujo realizado\n\nPaso 3: Anotar fecha y hora de cita\n\nPaso 4: Agregar notas relevantes\n\nPaso 5: Marcar como resuelto",
      nextStep: "step-completado",
      tip: "Documentar claramente todo el proceso para referencia futura",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-derivacion",
      title: "Derivar a Flujo Correspondiente",
      description: "Redirigir al paciente al proceso adecuado",
      type: "action",
      content: "Paso 1: Identificar el proceso correcto para el paciente\n\nPaso 2: Explicar al paciente el siguiente paso\n\nPaso 3: Transferir al departamento correspondiente\n\nPaso 4: Documentar la derivación",
      nextStep: "step-completado",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-completado",
      title: "Flujo PX sin Cita Completado",
      description: "Proceso para pacientes sin cita finalizado",
      type: "info",
      content: "El proceso de flujo para paciente sin cita con segundo pago próximo ha sido completado exitosamente.",
      estimatedTime: "1 minuto",
    },
  ],
  "proc-agendamiento-citas": [
    {
      id: "step-1",
      title: "Identificar Tipo de Cita",
      description: "Determinar si es primera vez o subsecuente",
      type: "question",
      content: "Preguntar al paciente: '¿Es su primera cita o es una cita subsecuente?'",
      options: [
        {
          id: "primera-vez",
          label: "Primera vez",
          nextStep: "step-agendar-primera-vez",
        },
        {
          id: "subsecuente",
          label: "Subsecuente",
          nextStep: "step-agendar-subsecuente",
        },
      ],
      estimatedTime: "1 minuto",
    },
    {
      id: "step-agendar-primera-vez",
      title: "Agendar Cita de Primera Vez",
      description: "Programar cita para paciente nuevo",
      type: "action",
      content: "Paso 1: Abrir Calendly\n\nPaso 2: Seleccionar tipo de cita 'Primera Vez (Long)'\n\nPaso 3: Buscar especialista disponible\n\nPaso 4: Mostrar horarios disponibles al paciente\n\nPaso 5: Seleccionar horario con paciente\n\nPaso 6: Llenar datos completos del paciente\n\nPaso 7: Confirmar agendamiento",
      nextStep: "step-confirmar-cita",
      estimatedTime: "4 minutos",
    },
    {
      id: "step-agendar-subsecuente",
      title: "Agendar Cita Subsecuente",
      description: "Programar cita de seguimiento",
      type: "action",
      content: "Paso 1: Abrir Calendly\n\nPaso 2: Seleccionar tipo de cita 'Subsecuente'\n\nPaso 3: Buscar especialista del paciente\n\nPaso 4: Verificar disponibilidad\n\nPaso 5: Mostrar horarios disponibles\n\nPaso 6: Seleccionar horario con paciente\n\nPaso 7: Confirmar agendamiento",
      nextStep: "step-confirmar-cita",
      estimatedTime: "3 minutos",
    },
    {
      id: "step-confirmar-cita",
      title: "Confirmar Detalles de Cita",
      description: "Verificar y confirmar información de la cita",
      type: "action",
      content: "Paso 1: Verificar fecha y hora seleccionada\n\nPaso 2: Confirmar nombre del especialista\n\nPaso 3: Validar datos del paciente\n\nPaso 4: Revisar tipo de cita correcto\n\nPaso 5: Confirmar todo con el paciente",
      nextStep: "step-enviar-confirmacion",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-enviar-confirmacion",
      title: "Enviar Confirmación",
      description: "Enviar confirmación de cita al paciente",
      type: "action",
      content: "Paso 1: Enviar confirmación automática de Calendly\n\nPaso 2: Verificar que el paciente reciba el correo\n\nPaso 3: Explicar cómo unirse a la cita (virtual)\n\nPaso 4: Proporcionar instrucciones para cita presencial\n\nPaso 5: Ofrecer contacto para cambios",
      nextStep: "step-documentar",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-documentar",
      title: "Documentar en Hubspot",
      description: "Registrar la cita en el sistema",
      type: "action",
      content: "Paso 1: Abrir perfil del paciente en Hubspot\n\nPaso 2: Crear nota de agendamiento\n\nPaso 3: Registrar fecha, hora y especialista\n\nPaso 4: Agregar tipo de cita\n\nPaso 5: Marcar como completado",
      nextStep: "step-completado",
      tip: "Documentar siempre para tener registro histórico",
      estimatedTime: "2 minutos",
    },
    {
      id: "step-completado",
      title: "Cita Agendada Exitosamente",
      description: "Proceso de agendamiento completado",
      type: "info",
      content: "La cita ha sido agendada exitosamente. El paciente ha recibido la confirmación y está registrado en el sistema.",
      estimatedTime: "1 minuto",
    },
  ],
}

// Procesos recientes para el dashboard
export const recentProcesses = [
  {
    id: "recent-1",
    title: "Cancelación de Paciente",
    category: "cancelacion",
    timestamp: "Hace 10 minutos",
    user: "Agente María González",
  },
  {
    id: "recent-2", 
    title: "Envío de Medicamento",
    category: "medicamento",
    timestamp: "Hace 25 minutos",
    user: "Agente Carlos Rodríguez",
  },
  {
    id: "recent-3",
    title: "Cambio Fecha de Pago",
    category: "pagos", 
    timestamp: "Hace 1 hora",
    user: "Agente Ana López",
  },
  {
    id: "recent-4",
    title: "Error en Dirección",
    category: "envios",
    timestamp: "Hace 2 horas",
    user: "Agente Pedro Martínez",
  },
  {
    id: "recent-5",
    title: "Agendamiento de Citas",
    category: "citas",
    timestamp: "Hace 3 horas",
    user: "Agente Laura Sánchez",
  },
]
